/**
 * Definição das actions do reducer responsável pelo gerenciamento das vendas
 */
export const ADD_SALE = 'ADD_SALE';
export const ADD_SALE_SUCCESS = 'ADD_SALE_SUCCESS';
export const ADD_SALE_FAIL = 'ADD_SALE_FAIL';
export const IMPORT_SALES = 'IMPORT_SALES';
export const IMPORT_SALES_SUCCESS = 'IMPORT_SALES_SUCCESS';
export const IMPORT_SALES_FAIL = 'IMPORT_SALES_FAIL';
export const UPDATE_SALE = 'UPDATE_SALE';
export const UPDATE_SALE_SUCCESS = 'UPDATE_SALE_SUCCESS';
export const UPDATE_SALE_FAIL = 'UPDATE_SALE_FAIL';
export const DELETE_SALE = 'DELETE_SALE';
export const DELETE_SALE_SUCCESS = 'DELETE_SALE_SUCCESS';
export const DELETE_SALE_FAIL = 'DELETE_SALE_FAIL';
export const GET_SALES_METRICS = 'GET_SALES_METRICS';
export const GET_SALES_METRICS_SUCCESS = 'GET_SALES_METRICS_SUCCESS';
export const GET_SALES_METRICS_FAIL = 'GET_SALES_METRICS_FAIL';
export const SEARCH_SALES = 'SEARCH_SALES';
export const SEARCH_SALES_SUCCESS = 'SEARCH_SALES_SUCCESS';
export const SEARCH_SALES_FAIL = 'SEARCH_SALES_FAIL';
export const SELECT_SALE = 'SELECT_SALE';